# redis-server.yml
version: '3.7'
services:
  dev:
    build:
      dockerfile: docker/dev/dockerfile
      context: .
    command: tail -f /dev/null
    # command: "python3 manage.py runserver 0.0.0.0:8000"
    # command: 'sh docker/dev/run.sh'
    container_name: ${CONTAINER_NAME}
    hostname: root
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '${PORT}:8000'
    restart: always
    working_dir: /usr/src/app
    environment:
      TZ: 'Asia/Seoul'
  build:
    build:
      dockerfile: docker/deploy/build.dockerfile
      context: .
    image: ${CONTAINER_NAME}:build
    container_name: ${CONTAINER_NAME}_build
    hostname: root
    working_dir: /usr/src/app
    environment:
      TZ: 'Asia/Seoul'
  jenkins:
    build:
      dockerfile: docker/deploy/dockerfile
      context: .
      args:
        CONTAINER_NAME: ${CONTAINER_NAME}
        PLATFORM: ${PLATFORM}
    healthcheck:
      test: ['curl', '-f', 'http://172.17.0.1:${PORT}']
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s
    entrypoint: 'sh docker/deploy/run.sh'
    container_name: ${CONTAINER_NAME}_deploy
    hostname: root
    volumes:
      - /var/run/celery:/var/run
      - /home/${USER}/nginx/data/runthe_backend/${CONTAINER_NAME}:/tmp/runthe_backend
      - /home/${USER}/nginx/data/runthe_backend/${CONTAINER_NAME}/static:/usr/src/app/static
    ports:
      - '${PORT}:8000'
    restart: unless-stopped
    working_dir: /usr/src/app
    environment:
      TZ: 'Asia/Seoul'
  deploy:
    build:
      dockerfile: docker/deploy/dockerfile
      context: .
      args:
        CONTAINER_NAME: ${CONTAINER_NAME}
        PLATFORM: ${PLATFORM}
    healthcheck:
      test: ['curl', '-f', 'http://172.17.0.1:${PORT}']
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s
    entrypoint: 'sh docker/deploy/run.sh'
    container_name: ${CONTAINER_NAME}_deploy
    # network_mode: host
    hostname: root
    volumes:
      - /var/run/celery:/var/run
      - /home/${USER}/nginx/data/runthe_backend/${CONTAINER_NAME}:/tmp/runthe_backend
      - /home/${USER}/nginx/data/runthe_backend/${CONTAINER_NAME}/static:/usr/src/app/static
    ports:
      - '${PORT}:8000'
    restart: unless-stopped
    working_dir: /usr/src/app
    environment:
      TZ: 'Asia/Seoul'
