# Generated by Django 4.1.3 on 2022-11-11 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('apikey', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Upstream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('request_path', models.CharField(max_length=255)),
                ('wrapped_path', models.CharField(max_length=255)),
                ('scheme', models.CharField(choices=[('http', 'Http'), ('https', 'Https'), ('http+unix', 'Unitx')], default='https', max_length=64)),
                ('plugin', models.IntegerField(choices=[(0, 'Remote auth'), (1, 'Basic auth'), (2, 'Key auth'), (3, 'Server auth')], default=0)),
                ('consumers', models.ManyToManyField(blank=True, to='apigateway.consumer')),
                ('upstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.upstream')),
            ],
        ),
    ]
