# Generated by Django 4.1.3 on 2022-11-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='scheme',
            field=models.CharField(choices=[('http', 'Http'), ('https', 'Https'), ('unix', 'Unitx')], default='https', max_length=64),
        ),
    ]
