# Generated by Django 3.2.9 on 2022-11-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstream',
            name='alias',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='api',
            name='plugin',
            field=models.IntegerField(choices=[(0, '토큰을 검사하지 않습니다'), (1, 'Basic auth'), (2, 'Key auth'), (3, '게이트웨이에서 토큰을 검사합니다. 어드민 만 접근가능합니다.')], default=0),
        ),
    ]
