# Generated by Django 3.2.9 on 2023-03-04 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0004_consumer_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstream',
            name='weight',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('scheme', models.CharField(choices=[('http', 'Http'), ('https', 'Https'), ('http+unix', 'Unitx')], default='http', max_length=64)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('upstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='apigateway.upstream')),
            ],
        ),
    ]
