# Generated by Django 3.2.9 on 2023-03-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0007_rename_enable_target_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='활성화'),
        ),
        migrations.AlterField(
            model_name='target',
            name='weight',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
