# Generated by Django 3.2.9 on 2023-03-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0008_auto_20230305_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstream',
            name='load_balance',
            field=models.CharField(choices=[('round_robin', 'Round Robin'), ('weight_robin', 'Weight Robin')], default='round_robin', max_length=64),
        ),
    ]
