# Generated by Django 3.2.9 on 2023-03-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0009_upstream_load_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='plugin',
            field=models.IntegerField(choices=[(0, '토큰을 검사하지 않습니다'), (1, 'Basic auth'), (2, 'Key auth'), (3, 'Admin only.')], default=0),
        ),
    ]
