# Generated by Django 3.2.9 on 2023-03-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0010_alter_api_plugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='plugin',
            field=models.IntegerField(choices=[(0, 'No auth'), (1, 'Basic auth'), (2, 'Key auth'), (3, 'Admin only.')], default=0),
        ),
    ]
