# Generated by Django 3.2.9 on 2023-03-06 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0011_alter_api_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstream',
            name='retries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstream',
            name='timeout',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='api',
            name='upstream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_set', to='apigateway.upstream'),
        ),
    ]
