# Generated by Django 3.2.9 on 2023-03-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0013_alter_upstream_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
