# Generated by Django 3.2.9 on 2023-03-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0014_alter_api_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='plugin',
            field=models.IntegerField(choices=[(0, 'No Auth'), (1, 'Basic Auth'), (2, 'Key Auth'), (3, 'Admin Only')], default=0),
        ),
    ]
