ARG CONTAINER_NAME
FROM $CONTAINER_NAME:build
USER root
WORKDIR /usr/src/app
ENV PYTHONUNBUFFERED=0
COPY . .
RUN echo yes | python3 manage.py collectstatic
##uwsgi.sock
RUN mkdir /tmp/uwsgi
##aws
# RUN mkdir ~/.aws
# COPY ./docker/deploy/.aws/config /root/.aws/credentials

ENTRYPOINT sh docker/deploy/run.sh